# Generated by Django 4.2 on 2025-02-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pssw', models.CharField(max_length=16)),
                ('cpssw', models.CharField(max_length=16)),
            ],
        ),
    ]
