# Generated by Django 4.2 on 2025-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnm', models.CharField(max_length=25)),
                ('prc', models.IntegerField()),
                ('pim', models.FileField(upload_to='pic')),
                ('des', models.TextField()),
            ],
        ),
    ]
