# Generated by Django 4.2 on 2025-02-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_pro_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_tbl',
            name='pim',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
