# Generated by Django 4.2 on 2025-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_pro_tbl_pim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpnm', models.CharField(max_length=30)),
                ('rprc', models.IntegerField()),
                ('rpim', models.ImageField(upload_to='rpic')),
                ('rdes', models.TextField()),
            ],
        ),
    ]
