# Generated by Django 4.2 on 2025-02-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rent_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.rent_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pro_tbl')),
            ],
        ),
    ]
