# Generated by Django 4.2 on 2025-02-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=25)),
                ('smobile', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('spssw', models.CharField(max_length=16)),
                ('scpssw', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='cart_tbl',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.reg_tbl'),
        ),
    ]
