# Generated by Django 4.2 on 2025-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_sell_tbl_alter_cart_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('issues', models.TextField()),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
