# Generated by Django 4.2 on 2025-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_service_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_tbl',
            name='name',
            field=models.CharField(default='unknown', max_length=25),
        ),
    ]
