# Generated by Django 4.2 on 2025-02-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_service_tbl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('raadhar', models.IntegerField()),
                ('rmobile', models.IntegerField()),
                ('rdate', models.DateField()),
                ('rmonths', models.CharField(max_length=25)),
            ],
        ),
    ]
