# Generated by Django 4.2 on 2025-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rental_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_tbl',
            name='rname',
            field=models.CharField(default='unknown', max_length=25),
        ),
    ]
