# Generated by Django 4.2 on 2025-02-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_rental_tbl_rname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_tbl',
            old_name='address',
            new_name='raddress',
        ),
    ]
