# Generated by Django 4.2 on 2025-02-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_rename_address_rental_tbl_raddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_pro_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pro_tbl')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.sell_tbl')),
            ],
        ),
    ]
