# Generated by Django 4.2 on 2025-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_sell_pro_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_tbl',
            name='raadhar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rental_tbl',
            name='rmobile',
            field=models.BigIntegerField(),
        ),
    ]
