# Generated by Django 4.2 on 2025-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_rental_tbl_raadhar_alter_rental_tbl_rmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_tbl',
            name='raadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental_tbl',
            name='rmobile',
            field=models.IntegerField(),
        ),
    ]
