# Generated by Django 4.2 on 2025-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_rental_tbl_ramount_alter_rental_tbl_raadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_tbl',
            name='ritem',
            field=models.CharField(default='item', max_length=80),
        ),
    ]
