# Generated by Django 4.2 on 2025-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_rental_tbl_ritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_tbl',
            name='rprice',
            field=models.IntegerField(default=0),
        ),
    ]
