# Generated by Django 4.2 on 2025-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_rental_tbl_rprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tbl',
            name='add',
            field=models.TextField(default='not entered'),
        ),
        migrations.AddField(
            model_name='reg_tbl',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
