# Generated by Django 4.2 on 2025-03-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_reg_tbl_add_reg_tbl_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pro_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.reg_tbl')),
            ],
        ),
    ]
