from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('register',views.reg),
    path('login',views.log),
    path('products',views.product,name='addproducts'),
    path('product2',views.product2,name='product2'),
    path('cart/<int:idn>',views.cart,name='cart'),
    path('rent',views.rent,name='addrentproduct'),
    path('rent2',views.rent2),
    path('viewcart',views.viewcart),
    path('cartdelete/<int:pid>',views.cartdelete,name='cartdelete'),
    path('cartpayment',views.cartpayment),
    path('rentpay/',views.rentpayment,name='rentpay'),
    path('clogin/',views.clogin,name='clogin'),
    path('logout/',views.logout_view,name='logout'),
    path('selreg',views.sell_reg),
    path('sellog',views.sell_log),
    path('prodetails',views.seller_pro_det,name='prodetails'),
    path('prodelete/<int:prid>',views.pro_delete,name='pro_delete'),
    path('edit/<int:ide>',views.edit,name='edit' ),
    path('update/<int:ide>',views.update,name='update'),
    path('adminlog/',views.admin_log ,name='adminlog'),
    path('reg_cus/',views.reg_cus_view,name='reg_cus'),
    path('reg_pro/',views.reg_pro_view,name='reg_pro'),
    path('cuedit/<int:idc>',views.reg_cus_edit,name='cusedit'),
    path('cudelete/<int:idc>',views.reg_cus_delete,name='cusdelete'),
    path('proedit/<int:idp>',views.reg_pro_edit,name='proedit'),
    path('adminlogout/',views.adm_logout,name='adm_logout'),
    path('rentbook/<int:idb>',views.rent_book,name='rent_book'),
    path('service',views.service_book),
    path('servicedata/',views.reg_ser_view,name='reg_ser'),
    path('sellercart',views.view_seller_pro),
    path('techassign/',views.tech_assin,name='tech'),
    path('rentdata/',views.reg_rent_view,name='reg_rent'),
    path('buy/<int:pid>/', views.buy, name='buy'),
    path('pay/<int:order_id>/', views.payment, name='pay'),
    path('process_payment/', views.payment, name='process_payment'),
    path('bookingdata/',views.reg_buy_view,name='reg_buy'),
    path('orders',views.my_orders),

]